//
//  MDKeyView.h
//  MegaDeck
//
//  Created by Lucas Kuzma on 3/24/12.
//  Copyright (c) 2012 The Strange Agency, LLC. All rights reserved.
//
//  Just the key surface portion of a keyboard, i.e. no other controls here
//  NOTE landscape mode does not support pretty chromatic keyboard

#import <UIKit/UIKit.h>
#import "MDKeyModel.h"

@protocol MDKeyProtocol <NSObject>

- (void) notePressed:(int)noteNumber withVelocity:(float)velocity;
- (void) noteReleased:(int)noteNumber;
- (void) afterTouch:(int)noteNumber withVelocity:(float)velocity;

@end

@interface MDKeyView : UIView <MDKeyModelProtocol>
{
	CFMutableDictionaryRef touchDictionary;
	id<MDKeyProtocol> delegate;
	BOOL isPrettyChromatic;
	BOOL isPortrait;
	
	float nKeys;
	float nLines;
	float keyWidth;
	float whiteWidth;
	float blackWidth;
	float keyHeight;
	float lineHeight;
	
	float keyAlpha;
}

@property (retain) id<MDKeyProtocol> delegate;
@property BOOL isPrettyChromatic;
@property (nonatomic) BOOL isPortrait;
@property float keyAlpha;

- (int)noteNumberForTouch:(UITouch*)touch;
- (float)velocityForTouch:(UITouch*)touch;

/**
 * static mechanism to allow one instance to handle touches generated by several instances
 * e.g. to hightlight touched keys on just one instance
 */
+ (MDKeyView*)sharedTouchHandler:(MDKeyView*)handler;
- (void)handleSharedTouches:(NSSet*)touches;

@end
